### PR TITLE
PR: Create INSTALLATION.md and setup.py

### LINKED ISSUE #6: installation
i think it would be useful to make some youtube videos on the installation of crocrodile.

### PR DESCRIPTION
**Pull request by vibranium21**
# Crocrodile
### Description
Create INSTALLATION.md an setup.py files to install Crocrodile.
### To Do
- [x] Create `INSTALLATION.md`
- [x] Create `setup.py`
- [x] Test `setup.py`
- [ ] Test Windows compatibility
###### Crocrodile 3.0 - Fixes #6

### CODE REVIEW

**Comment by vibranium21** [comment]
setup.py already exists

**Comment by Virinas-code** [comment]
But with old CxFreeze

**Comment by vibranium21** [comment]
1. Download The [code](https://codeload.github.com/virinas-code/crocrodile/zip/refs/heads/master) step one for when you get around to making file :)

**Review by Virinas-code — APPROVED** [review]

**Review by Virinas-code — APPROVED** [review]

**Review by Virinas-code — APPROVED** [review]

**Comment by Virinas-code** [comment]
This is now priority.

**Comment by Virinas-code** [comment]
@vibranium21 Can you remake ̀INSTALLATION.md` with latest changes ?

**Review by Virinas-code — CHANGES_REQUESTED** [review]
New repository : Virinas-code/crocrodile-easy. Great work, can you put the link of this repository in the INSTALLATION.md file ?

**Pull request closed without merging**
